### ISSUE TITLE
Atualizar nvidia-docker

### ISSUE THREAD

**Issue by tiagoshibata** [ThundeRatz/container-deploy#6]
[NVIDIA/nvidia-docker](https://github.com/NVIDIA/nvidia-docker)

Eles lançaram um `nvidia-docker2` que é diferente (tem features a mais e integra como um runtime do docker ao invés de ser um wrapper que chama o docker). Seria interessante portar na próxima vez que formos rodar algo em CUDA.

**Comment by tiagoshibata** [comment]
Por compatibilidade, eles mantiveram `nvidia-docker` como um script que chama `docker --runtime=nvidia`:

```bash
$ cat `which nvidia-docker`
#! /bin/bash
# Copyright (c) 2017, NVIDIA CORPORATION. All rights reserved.

NV_DOCKER=${NV_DOCKER:-"docker"}

DOCKER_ARGS=""
NV_DOCKER_ARGS=""
while [ $# -gt 0 ]; do
    arg=$1
    shift
    DOCKER_ARGS="$DOCKER_ARGS $arg"
    case $arg in
        run|create)
            NV_DOCKER_ARGS="--runtime=nvidia"
            if [ ! -z $NV_GPU ]; then
                NV_DOCKER_ARGS="$NV_DOCKER_ARGS -e NVIDIA_VISIBLE_DEVICES=${NV_GPU// /,}"
            fi
            break
        ;;
        version)
            printf "NVIDIA Docker: 2.0.0\n"
            break
        ;;
    esac
done

if [ ! -z $NV_DEBUG ]; then
    set -x
fi

$NV_DOCKER $DOCKER_ARGS $NV_DOCKER_ARGS "$@"
```

Aparentemente é compatível com a versão antiga, talvez seja só uma questão de atualizar o pacote e testar se não quebrou nada

**Comment by d-nery** [comment]
isso aqui ainda faz sentido? pode fechar?

**Comment by erickotsuka** [comment]
Acho que não faz sentido do jeito que está porque o nvidia-docker2 já está deprecated. Ou seja, é bom atualizar para uma versão ainda mais nova.

**Comment by tiagoshibata** [comment]
Mas continua tendo que atualizar, ué. A issue é a mesma hahaha, mas vcs não tem usado o container, né?
